### ISSUE TITLE
Hangs when used with gina.vim

### ISSUE THREAD

**Issue by kuuote** [hrsh7th/vim-candle#5]
本プラグインを導入した状態で[Gina.vim](https://github.com/lambdalisue/gina.vim) を導入し`:Gina status`を実行するとハングアップします。

使用したコミット及びVimのバージョンは以下の通りになります。

aa50401
lambdalisue/gina.vim@dd5340e
Vim 8.2.364

**Comment by hrsh7th** [comment]
別の場所で `while-sleep` を利用するプラグインが複数あるとハングするのではないか？ という仮説を上げましたが。全然違ったようです。

普通に expand('%') がファイルではないケースの考慮漏れだったので修正を行いました。

ご報告ありがとうございました。
https://github.com/hrsh7th/vim-candle/commit/857ced133db3335bdac5ad50fd926163b9bab0a0
